query Projects {
  allProject {
    title
    _createdAt
    slug {
      current
    }
    tags {
      tagName
    }
    hero {
      contentUrl
    }
    details {
      client
      project
      projectType
      date
    }
  }
}
